import { useMemo, useState } from "react";
import { Link } from "wouter";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowUpRight, Check, ChevronRight, CircleHelp, Clock3, Download, FileUp, Filter, GitBranch, Layers3, MoreHorizontal, Play, Plus, Search, ShieldCheck, Sparkles, UploadCloud, X, Zap } from "lucide-react";
import { toast } from "sonner";
import { AppShell, SectionHeading, StatusChip } from "@/components/qaflow/AppShell";
import { attention, bugs, coverage, environments, metrics, requirements, runs, testCases, trend } from "@/data/mockQaData";

function Button({ children, primary = false, onClick, icon }: { children: React.ReactNode; primary?: boolean; onClick?: () => void; icon?: React.ReactNode }) { return <button className={primary ? "primary-button" : "secondary-button"} onClick={onClick}>{icon}{children}</button>; }

export function Overview() {
  const [drawer, setDrawer] = useState(false); const [dialog, setDialog] = useState<"prd" | "run" | null>(null);
  return <AppShell title="Overview" eyebrow="QUALITY CONTROL ROOM" action={<><Button icon={<FileUp size={15} />} onClick={() => setDialog("prd")}>Upload PRD</Button><Button primary icon={<Play size={15} />} onClick={() => setDialog("run")}>Run smoke suite</Button></>}>
    <div className="metric-grid">{metrics.map((metric) => <div className="metric-card" key={metric.label}><div className="metric-label">{metric.label}</div><div className="metric-value">{metric.value}</div><div className="metric-foot"><em className={metric.tone}>{metric.delta}</em><span className="metric-detail">{metric.detail}</span></div></div>)}</div>
    <div className="dashboard-grid"><div className="panel"><SectionHeading title="Pass rate & execution duration" detail="14 hari terakhir" action={<button className="text-link" onClick={() => toast("Report detail", { description: "Membuka aggregate quality report." })}>View report <ArrowUpRight size={12} /></button>} /><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{ top: 4, right: 8, left: -22, bottom: 0 }}><defs><linearGradient id="passFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#B7F36B" stopOpacity={.45}/><stop offset="95%" stopColor="#B7F36B" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#E8ECE8" strokeDasharray="3 3"/><XAxis dataKey="day" tick={{ fontSize: 9, fill: "#84918B" }} tickLine={false} axisLine={false} interval={2}/><YAxis domain={[80,100]} tick={{ fontSize: 9, fill: "#84918B" }} tickLine={false} axisLine={false}/><Tooltip contentStyle={{ borderRadius: 8, border: "1px solid #E4E8E3", fontSize: 11 }} /><Area type="monotone" dataKey="pass" stroke="#6D9C25" fill="url(#passFill)" strokeWidth={2.5} name="Pass rate %" /><Area type="monotone" dataKey="duration" stroke="#5B8DEF" fill="none" strokeWidth={2} name="Duration / min" /></AreaChart></ResponsiveContainer></div><div className="legend"><span><i style={{background:"#6D9C25"}}/> Pass rate</span><span><i style={{background:"#5B8DEF"}}/> Duration</span><span style={{marginLeft:"auto"}}>Target <b>≥ 95%</b></span></div></div><div className="panel"><SectionHeading title="Requirement coverage" detail="224 total requirements" action={<Link href="/requirements" className="text-link">View all <ArrowUpRight size={12} /></Link>} />{coverage.map((item) => <div className="coverage-row" key={item.label}><div className="coverage-top"><span>{item.label}</span><span>{item.value}% · {item.count}</span></div><div className="bar"><i className={item.tone} style={{width:`${item.value}%`}} /></div></div>)}<div style={{borderTop:"1px solid #EEF0ED",paddingTop:14,marginTop:22,display:"flex",justifyContent:"space-between",alignItems:"center"}}><span className="subtext">Coverage naik sejak PRD v12 diproses</span><span className="status-chip status-lime">+6.0%</span></div></div></div>
    <div className="dashboard-grid"><div className="panel table-panel"><SectionHeading title="Recent test runs" detail="Latest activity across environments" action={<Link href="/runs" className="text-link">All runs <ArrowUpRight size={12} /></Link>} /><RunTable compact onRow={() => setDrawer(true)} /></div><div className="panel"><SectionHeading title="Needs attention" detail="Prioritas untuk hari ini" />{attention.map((item) => <div className={`attention-item tone-${item.tone}`} key={item.title} onClick={() => toast(item.action, { description: item.title })}><span className="eyebrow">{item.eyebrow}</span><h3>{item.title}</h3><p>{item.detail}</p><div className="attention-action">{item.action} <ChevronRight size={11} /></div></div>)}</div></div>
    {drawer && <TraceDrawer onClose={() => setDrawer(false)} />}{dialog === "prd" && <UploadDialog onClose={() => setDialog(null)} />}{dialog === "run" && <RunDialog onClose={() => setDialog(null)} />}
  </AppShell>;
}

function RunTable({ compact = false, onRow }: { compact?: boolean; onRow?: () => void }) { return <table className="data-table"><thead><tr><th>Run</th><th>Status</th><th>Environment</th><th>Result</th><th>Duration</th><th>Triggered by</th><th /></tr></thead><tbody>{runs.slice(0, compact ? 5 : runs.length).map((run) => <tr key={run.id} onClick={onRow} style={{cursor:onRow?"pointer":"default"}}><td><span className="id-code">{run.id}</span><span className="subtext">{run.title}</span></td><td><StatusChip status={run.status} /></td><td><span className="tag">{run.env}</span></td><td><strong>{run.pass}</strong></td><td>{run.duration}</td><td><span className="subtext">{run.trigger}</span><span className="subtext">{run.time}</span></td><td><MoreHorizontal size={15} color="#A7B1AC" /></td></tr>)}</tbody></table>; }

function TraceDrawer({ onClose }: { onClose: () => void }) { return <><div className="drawer-scrim" onClick={onClose}/><aside className="trace-drawer"><button className="icon-button drawer-close" onClick={onClose} aria-label="Tutup detail"><X size={17}/></button><span className="eyebrow">RUN DETAIL · RUN-127</span><h2 style={{fontSize:22,margin:"9px 0 6px"}}>Checkout regression</h2><p style={{color:"#6B7A8D",fontSize:11,margin:0}}>staging · triggered by Aisha Rahman · 1 jam lalu</p><div style={{display:"flex",gap:8,marginTop:18}}><StatusChip status="failed"/><span className="tag">31 / 36 passed</span><span className="tag">14m 18s</span></div><div className="trace-line"><div className="trace-node"><h4>REQ-043 · Payment validation</h4><p>3 linked test cases · 2 approved</p></div><div className="trace-node"><h4>TC-0046 · Tolak kartu kadaluarsa</h4><p>API assertion failed on retry #2</p></div><div className="trace-node"><h4>Fingerprint 7f2a9c</h4><p>5 occurrences across 2 runs · likely duplicate</p></div><div className="trace-node"><h4>BUG-219 · Jira PAY-882</h4><p>Open · High severity · last seen 12 menit lalu</p></div></div><div style={{display:"flex",gap:8,marginTop:5}}><Button onClick={() => toast("Rerun queued", {description:"5 failed test akan dijalankan ulang di staging."})} icon={<Play size={14}/>}>Rerun failed</Button><Button primary onClick={() => toast("Bug already linked", {description:"Fingerprint 7f2a9c telah ditautkan ke Jira PAY-882."})} icon={<BugIcon/>}>Create bug</Button></div></aside></>; }
function BugIcon(){return <span style={{fontSize:14}}>!</span>}
function UploadDialog({ onClose }: { onClose: () => void }) { return <div className="dialog-backdrop"><div className="dialog-card"><div className="dialog-head"><div><span className="eyebrow">PRD INGESTION</span><h2>Upload product requirements</h2><p>QAflow akan mengekstrak requirement dan menyimpannya sebagai draft untuk direview.</p></div><button className="icon-button" onClick={onClose} aria-label="Tutup"><X size={17}/></button></div><div className="dropzone"><UploadCloud size={24}/><strong>Drop PRD di sini atau pilih file</strong><p>Markdown, PDF, atau DOCX · Maks. 25 MB</p></div><div className="dialog-actions"><Button onClick={onClose}>Cancel</Button><Button primary onClick={() => { onClose(); toast("PRD queued for extraction", {description:"PRD v13 masuk antrean parsing. Requirement baru akan muncul sebagai draft."}); }} icon={<FileUp size={14}/>}>Start extraction</Button></div></div></div>; }
function RunDialog({ onClose }: { onClose: () => void }) { return <div className="dialog-backdrop"><div className="dialog-card"><div className="dialog-head"><div><span className="eyebrow">NEW TEST RUN</span><h2>Run smoke suite</h2><p>Hanya test case approved dengan automation aktif yang akan dijalankan.</p></div><button className="icon-button" onClick={onClose} aria-label="Tutup"><X size={17}/></button></div><div className="module-grid" style={{gridTemplateColumns:"1fr 1fr",marginTop:4}}><label className="field-label">Environment<select className="filter-select"><option>staging</option><option>dev</option></select></label><label className="field-label">Browser<select className="filter-select"><option>Chromium</option><option>Firefox</option></select></label></div><div className="run-summary"><span><ShieldCheck size={15}/> 42 eligible test cases</span><span><Zap size={15}/> 4 workers · 1 retry</span></div><div className="dialog-actions"><Button onClick={onClose}>Cancel</Button><Button primary onClick={() => { onClose(); toast("Run queued", {description:"RUN-129 dibuat dan akan berjalan di staging."}); }} icon={<Play size={14}/>}>Queue run</Button></div></div></div>; }

export function ModulePage({ kind }: { kind: "requirements" | "test-cases" | "runs" | "reports" | "bugs" | "environments" | "integrations" }) {
  const [query, setQuery] = useState(""); const [activeTab, setActiveTab] = useState("All"); const [drawer, setDrawer] = useState(false); const [dialog, setDialog] = useState<"prd" | "run" | null>(null);
  const config = { requirements: { title:"Requirements", eyebrow:"PRD → TRACEABILITY", description:"Satu sumber kebenaran untuk kebutuhan produk dan coverage testing.", cta:"Upload PRD", icon:FileTextIcon }, "test-cases": { title:"Test Cases", eyebrow:"AUTHORING WORKSPACE", description:"Skenario terstruktur yang siap direview, diotomasi, dan dijalankan.", cta:"Generate test cases", icon:Layers3 }, runs: { title:"Test Runs", eyebrow:"EXECUTION CONTROL ROOM", description:"Pantau eksekusi deterministik di seluruh environment.", cta:"Run suite", icon:Play }, reports: { title:"Reports", eyebrow:"QUALITY INTELLIGENCE", description:"Trend, coverage, dan bukti rilis dalam satu tempat.", cta:"Export report", icon:Download }, bugs: { title:"Bug Inbox", eyebrow:"FAILURE → ACTION", description:"Failure cluster yang sudah dideduplikasi untuk ditindaklanjuti.", cta:"Create bug", icon:BugIcon }, environments: { title:"Environments", eyebrow:"SAFE EXECUTION", description:"Target environment, allowlist, dan guardrail eksekusi.", cta:"Add environment", icon:ServerIcon }, integrations: { title:"Integrations", eyebrow:"CONNECTED WORKFLOWS", description:"Hubungkan QAflow ke tracker dan pipeline tim engineering.", cta:"Add integration", icon:PlugIcon } }[kind];
  const filteredReq = requirements.filter((item) => item.title.toLowerCase().includes(query.toLowerCase()) || item.id.toLowerCase().includes(query.toLowerCase()));
  const filteredTc = testCases.filter((item) => item.title.toLowerCase().includes(query.toLowerCase()) || item.id.toLowerCase().includes(query.toLowerCase()));
  return <AppShell title={config.title} eyebrow={config.eyebrow} action={<Button primary onClick={() => kind === "requirements" ? setDialog("prd") : kind === "runs" ? setDialog("run") : toast(config.cta, {description:"Action siap dihubungkan ke API platform."})} icon={<Plus size={15}/>}>{config.cta}</Button>}>
    {kind === "reports" ? <ReportsContent /> : kind === "bugs" ? <BugsContent onOpen={() => setDrawer(true)} /> : kind === "environments" ? <EnvironmentsContent /> : kind === "integrations" ? <IntegrationsContent /> : <div className="page-card"><div className="filter-row"><div style={{position:"relative"}}><Search size={14} style={{position:"absolute",left:10,top:10,color:"#8A9891"}}/><input className="filter-input" style={{paddingLeft:31}} placeholder="Search by ID or title" value={query} onChange={(e) => setQuery(e.target.value)} /></div>{(kind === "requirements" ? ["All","Needs coverage","Changed","Covered"] : ["All","Draft","In review","Approved"]).map(tab => <button key={tab} className={`filter-tab ${activeTab===tab?"active":""}`} onClick={() => setActiveTab(tab)}>{tab}</button>)}<button className="secondary-button" style={{padding:"8px 10px"}} onClick={() => toast("Filters", {description:"Filter drawer tersedia pada versi API."})}><Filter size={14}/> Filters</button><span className="filter-count">{kind === "requirements" ? filteredReq.length : filteredTc.length} items</span></div>{kind === "requirements" ? <RequirementsTable rows={filteredReq} onOpen={() => setDrawer(true)} /> : kind === "test-cases" ? <TestCaseTable rows={filteredTc} onOpen={() => setDrawer(true)} /> : <RunTable onRow={() => setDrawer(true)} />}</div>}
    {drawer && <TraceDrawer onClose={() => setDrawer(false)} />}{dialog === "prd" && <UploadDialog onClose={() => setDialog(null)} />}{dialog === "run" && <RunDialog onClose={() => setDialog(null)} />}
  </AppShell>;
}
function RequirementsTable({ rows, onOpen }: { rows: typeof requirements; onOpen: () => void }) { return <table className="data-table"><thead><tr><th>Requirement</th><th>Category</th><th>Priority</th><th>Coverage</th><th>Test cases</th><th>Source</th><th /></tr></thead><tbody>{rows.map(item => <tr key={item.id} onClick={onOpen} style={{cursor:"pointer"}}><td><span className="id-code">{item.id}</span><span className="row-title subtext">{item.title}</span>{item.changed && <span className="subtext" style={{color:"#A96D05"}}>Changed in v12</span>}</td><td>{item.category}</td><td><span className={`tag ${item.priority.toLowerCase()}`}>{item.priority}</span></td><td><StatusChip status={item.coverage === "covered" ? "approved" : item.coverage === "review" ? "review" : "failed"}/></td><td>{item.tests}</td><td><span className="subtext">{item.source}</span></td><td><ChevronRight size={15} color="#A7B1AC"/></td></tr>)}</tbody></table>; }
function TestCaseTable({ rows, onOpen }: { rows: typeof testCases; onOpen: () => void }) { return <table className="data-table"><thead><tr><th>Test case</th><th>Type</th><th>Status</th><th>Requirement</th><th>Automation</th><th>Steps</th><th /></tr></thead><tbody>{rows.map(item => <tr key={item.id} onClick={onOpen} style={{cursor:"pointer"}}><td><span className="id-code">{item.id}</span><span className="row-title subtext">{item.title}</span><span className="subtext">AI reason · {item.reason}</span></td><td><span className="tag">{item.type}</span></td><td><StatusChip status={item.status}/></td><td><span className="id-code">{item.requirement}</span></td><td>{item.automation ? <span className="status-chip status-lime">YES</span> : <span className="tag">MANUAL</span>}</td><td>{item.steps}</td><td><ChevronRight size={15} color="#A7B1AC"/></td></tr>)}</tbody></table>; }
function ReportsContent(){return <><div className="metric-grid">{metrics.slice(0,3).map(m=><div className="metric-card" key={m.label}><div className="metric-label">{m.label}</div><div className="metric-value">{m.value}</div><div className="metric-foot"><em className={m.tone}>{m.delta}</em><span className="metric-detail">{m.detail}</span></div></div>)}</div><div className="panel"><SectionHeading title="Quality trend" detail="Export-ready aggregate report" action={<Button icon={<Download size={14}/>} onClick={()=>toast("Export queued",{description:"Report Markdown sedang disiapkan."})}>Export</Button>}/><div className="chart-wrap" style={{height:280}}><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><CartesianGrid vertical={false} stroke="#E8ECE8" strokeDasharray="3 3"/><XAxis dataKey="day" tick={{fontSize:9,fill:"#84918B"}} tickLine={false} axisLine={false}/><YAxis tick={{fontSize:9,fill:"#84918B"}} tickLine={false} axisLine={false}/><Area type="monotone" dataKey="pass" stroke="#6D9C25" fill="#EAF7D8" strokeWidth={2.5}/></AreaChart></ResponsiveContainer></div></div></>}
function BugsContent({onOpen}:{onOpen:()=>void}){return <div className="page-card"><div className="filter-row"><button className="filter-tab active">All bugs · 7</button><button className="filter-tab">Open · 7</button><button className="filter-tab">Resolved · 18</button><span className="filter-count">Fingerprint deduplication on</span></div><table className="data-table"><thead><tr><th>Bug</th><th>Severity</th><th>Status</th><th>Fingerprint</th><th>Occurrences</th><th>Tracker</th><th /></tr></thead><tbody>{bugs.map(b=><tr key={b.id} onClick={onOpen} style={{cursor:"pointer"}}><td><span className="id-code">{b.id}</span><span className="row-title subtext">{b.title}</span><span className="subtext">Last seen {b.lastSeen}</span></td><td><span className={`tag ${b.severity.toLowerCase()}`}>{b.severity}</span></td><td><StatusChip status="open"/><span className="subtext">{b.status}</span></td><td><span className="id-code">{b.fingerprint}</span></td><td>{b.occurrences}×</td><td>{b.tracker}</td><td><ChevronRight size={15} color="#A7B1AC"/></td></tr>)}</tbody></table></div>}
function EnvironmentsContent(){return <div className="module-grid">{environments.map(env=><div className="info-card" key={env.name}><div className="info-top"><div className="info-icon"><ServerIcon/></div><StatusChip status={env.production?"review":"passed"}/></div><h3>{env.name}</h3><p style={{fontFamily:"IBM Plex Mono, monospace",fontSize:10,marginBottom:15}}>{env.url}</p><p>Allowed hosts · {env.hosts}<br/>Last check · {env.last}</p><div style={{marginTop:18,display:"flex",gap:7}}><Button onClick={()=>toast("Connection test",{description:`${env.name} connection healthy.`})}>Test connection</Button>{env.production&&<span className="tag high" style={{display:"flex",alignItems:"center"}}>Protected</span>}</div></div>)}</div>}
function IntegrationsContent(){return <div className="module-grid"><div className="info-card"><div className="info-top"><div className="info-icon"><GitBranch size={16}/></div><StatusChip status="passed"/></div><h3>Jira Software</h3><p>Automatic bug creation, fingerprint deduplication, and status sync.</p><div style={{marginTop:18}}><Button onClick={()=>toast("Jira mapping",{description:"Project PAY · Issue type Bug · Label qaflow"})}>Configure mapping</Button></div></div><div className="info-card"><div className="info-top"><div className="info-icon" style={{background:"#EAF0FF",color:"#5274B8"}}><PlugIcon/></div><span className="tag">NOT CONNECTED</span></div><h3>ClickUp</h3><p>Connect a second tracker for teams that manage bugs in ClickUp.</p><div style={{marginTop:18}}><Button primary onClick={()=>toast("Integration setup",{description:"OAuth handoff akan tersedia saat API aktif."})}>Connect ClickUp</Button></div></div><div className="info-card"><div className="info-top"><div className="info-icon" style={{background:"#FFF5DF",color:"#A96D05"}}><BellIcon/></div><span className="tag">OPTIONAL</span></div><h3>Notifications</h3><p>Slack, Teams, dan email untuk event run.finished dan bug.created.</p><div style={{marginTop:18}}><Button onClick={()=>toast("Notifications",{description:"Pilih channel notifikasi setelah webhook dikonfigurasi."})}>Add channel</Button></div></div></div>}
function FileTextIcon(){return <FileUp size={16}/>} function ServerIcon(){return <ServerIconBase/>} function ServerIconBase(){return <CircleHelp size={16}/>} function PlugIcon(){return <GitBranch size={16}/>} function BellIcon(){return <CircleHelp size={16}/>}
